export const FETCH_PRODUCTS = "FETCH_PRODUCT";
export const FETCH_PRODUCTS_SUCCESSFUL = "FETCH_PRODUCTS_SUCCESSFUL";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_SUCCESSFUL = "FETCH_CATEGORIES_SUCCESSFUL";
export const FETCH_CATEGORIES_FAILED = "FETCH_CATEGORIES_FAILED";